Repository n2n-milstein/inventory, pull requests merged in 2020-05, with the labels that each got.

#48 add eslint rule to ignore linebreak styles
  .eslintrc.js
Labels: code

#47 Finish interface to view and edit furniture
  package-lock.json
  package.json
  src/components/EditCard.vue
  src/components/EditCard/AttributeQuestion.vue
  src/components/EditCard/AttributeQuestions.vue
  src/components/EditCard/ConditionalDate.vue
  src/components/EditCard/DatePickerMenu.vue
  src/components/EditCard/PhysicalAttributes.vue
  src/components/EditCard/TimingDates.vue
  src/data/furniture/Timing.ts
  src/store/index.ts
  src/store/inventory/actions.ts
  src/store/inventory/getters.ts
  src/store/inventory/index.ts
  src/store/inventory/mutations.ts
  src/store/inventory/types.ts
  src/views/Inventory.vue
Labels: BIG, feature

#49 Edit card improvements
  src/components/EditCard.vue
  src/components/EditCard/ViewActions.vue
  src/components/InventoryActions.vue
  src/store/inventory/actions.ts
  src/store/inventory/getters.ts
  src/views/Inventory.vue
Labels: design, feature

#50 Inventory actions improvements
  src/components/InventoryActions.vue
  src/views/Inventory.vue
Labels: design, feature
