Repository n2n-milstein/inventory, pull requests merged in 2020-03, with the labels that each got.

#34 Inventory view and edit dialog
  src/components/AdminDialog.vue
  src/components/EditCard.vue
  src/components/EditCard/AttributeQuestion.vue
  src/components/EditCard/ConditionalDate.vue
  src/components/EditCard/DatePickerMenu.vue
  src/components/EditCard/PhysicalAttr.vue
  src/plugins/vuetify.ts
  src/styles/_global.scss
  src/views/Admin.vue
  src/views/Inventory.vue
Labels: BIG, code, feature

#36 Dynamic title in navigation bar & renamed Approvals to Pending
  public/index.html
  src/components/Navigation.vue
  src/router.ts
  src/views/Pending.vue
Labels: design, feature

#37 Update attribute text and symbols
  src/components/ApprovalCard.vue
  src/data/Furniture.ts
Labels: design, feature

#38 Update editor configurations
  .editorconfig
  .vscode/settings.json
Labels: code
